version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - 'env'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/var/lib/redis/data
    env_file:
      - 'env'

  app:
    build: ./blue-shorter
    command: /bin/bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
        - ./blue-shorter:/app
    ports:
        - "3000:3000"
    env_file:
        - 'env'
    depends_on:
        - postgres
        - redis
        - sidekiq
    tty: true
    stdin_open: true

  front:
    build: ./blue-shorter-app
    command: /bin/bash -c "yarn start"
    volumes:
        - ./blue-shorter-app:/app
    ports:
        - "3001:3001"
    env_file:
        - 'env'
    depends_on:
        - app
    tty: true
    stdin_open: true

  sidekiq:
    build: ./blue-shorter
    command: /bin/bash -c "bundle exec sidekiq"
    volumes:
        - ./blue-shorter:/app
    env_file:
        - 'env'
    depends_on:
        - postgres
        - redis
    tty: true
    stdin_open: true

volumes:
  redis:
  postgres:
